version: "3.8"
services:
  virtual-browser:
    image: "khaleeluddin/virtual-browser:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8081:8080"
    environment:
      - DISPLAY=:99
    command: >
      sh -c "Xvfb :99 -screen 0 1920x1080x24 &
             sleep 2 &&
             firefox --kiosk --width 1920 --height 1080"
